# config/blacklight.yml

# =============================================================================
# Settings not directly related to a specific Rails environment.
# =============================================================================

_solr:                                                                    &SOLR
  adapter:      solr
  http_adapter: httpclient

# Production Solr instance (UVa on-Grounds or via VPN).
_solr_uva_prod:                                                  &SOLR_UVA_PROD
  <<: *SOLR
  url: http://solr.lib.virginia.edu:8082/solr/core

# Development Solr instance (UVa on-Grounds or via VPN).
_solr_uva_dev:                                                    &SOLR_UVA_DEV
  <<: *SOLR
  url: http://solrtest.lib.virginia.edu:8082/solr/core

# Local development fake Solr instance.
_solr_local:                                                        &SOLR_LOCAL
  <<: *SOLR
  url: <%=
    ENV['SOLR_URL'] ||
    "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/blacklight-core"
  %>

# =============================================================================
# Desktop development configurations (UVa on-Grounds or via VPN)
# =============================================================================

# For the 'production' Rails environment (local).
production:                                                    &SOLR_LOCAL_PROD
  <<: *SOLR_UVA_PROD
  #<<: *SOLR_LOCAL

# For the 'development' Rails environment (local).
development:                                                    &SOLR_LOCAL_DEV
  <<: *SOLR_UVA_PROD
  #<<: *SOLR_LOCAL

# For the 'test' Rails environment (local).
test:                                                          &SOLR_LOCAL_TEST
  <<: *SOLR_UVA_PROD
  #<<: *SOLR_LOCAL
