# config/blacklight.yml

# =============================================================================
# Settings not directly related to a specific Rails environment.
# =============================================================================

# Production Solr instance (UVa on-Grounds or via VPN).
_solr_prod_uva:                                               &SOLR_PROD_UVALIB
  adapter: solr
  url: http://solr.lib.virginia.edu:8082/solr/core

# Development Solr instance (UVa on-Grounds or via VPN).
_solr_dev_uva:                                                 &SOLR_DEV_UVALIB
  adapter: solr
  url: http://solrtest.lib.virginia.edu:8082/solr/core

# Local development fake Solr instance.
_solr_local:                                                        &SOLR_LOCAL
  adapter: solr
  url: <%=
    ENV['SOLR_URL'] ||
    "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/blacklight-core"
  %>

# =============================================================================
# Desktop development configurations (UVa on-Grounds or via VPN)
# =============================================================================

# For the 'production' Rails environment (local).
production:                                                         &PROD_LOCAL
  <<: *SOLR_PROD_UVALIB
  #<<: *SOLR_LOCAL

# For the 'development' Rails environment (local).
development:                                                         &DEV_LOCAL
  <<: *SOLR_PROD_UVALIB
  #<<: *SOLR_LOCAL

# For the 'test' Rails environment (local).
test:                                                               &TEST_LOCAL
  <<: *SOLR_PROD_UVALIB
  #<<: *SOLR_LOCAL
